[window]
startup_mode = "maximized"

[env]
COLORTERM = "truecolor"

[cursor]
style = { shape = "Block", blinking = "Always" }

[font]
size = 16.5

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"
